"""Add hash column in the transaction table

Revision ID: 0cebae1303d9
Revises: 19f8bc2ea8a5
Create Date: 2024-09-12 15:58:31.124864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cebae1303d9'
down_revision: Union[str, None] = '19f8bc2ea8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'hash')
    # ### end Alembic commands ###
