"""Add bank_institution and bank_account table

Revision ID: 19f8bc2ea8a5
Revises: 99c7a0bba3ec
Create Date: 2024-09-04 16:07:03.139947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f8bc2ea8a5'
down_revision: Union[str, None] = '99c7a0bba3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banking_institution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('banking_institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banking_institution_id'], ['banking_institution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_account')
    op.drop_table('banking_institution')
    # ### end Alembic commands ###
