"""Add the transaction_type column to the transaction table

Revision ID: 99c7a0bba3ec
Revises: f70fae8d01de
Create Date: 2024-09-01 23:00:51.495526

"""

from email.policy import default
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99c7a0bba3ec"
down_revision: Union[str, None] = "f70fae8d01de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Étape 1: Ajouter une nouvelle colonne nullable temporaire
    op.add_column(
        "transaction",
        sa.Column("transaction_type", sa.String(), nullable=True, default="debit"),
    )

    # Étape 2: Mettre à jour la colonne temporaire avec les valeurs appropriées
    op.execute(
        """
        UPDATE "transaction"
        SET transaction_type = CASE
            WHEN product = "credit card" AND amount > 0 THEN "debit"
            WHEN product = "check account" AND amount > 0 THEN "debit"
            WHEN product = "credit card" AND amount < 0 THEN "credit"
            ELSE NULL  -- Pour les lignes sans correspondance
        END
    """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "transaction_type")
    # ### end Alembic commands ###
